config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  # get 'homepage', to: 'home#homepage'
  namespace :admin do
    resources :users do
      get :delete_modal
    end
    resources :products
    resources :categories
    resources :coupons
    resources :orders, only: %i[index show]
  end

  namespace :user do
    resources :products, only: %i[index]
    # since this cart is belongs to user and a user can only have a single cart so it should be resouce not resouces
    # as we do not have to pass any id to it, we can get the cart per user by using current_user.ensure_cart
    resource :cart, only: %i[show destroy]
    resources :order_items, only: %i[new create show destroy]
    resources :orders
  end
  post 'payments/create', to: 'payments#create'
  resources :invitations

  namespace :api do
    post :auth, to: 'authentication#create'
    namespace :admin do
      resources :users
      resources :products
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

# Order model
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  enum payment: %i[cash card]
  enum status: %i[complete pending]
  validates :name, :email, :address, presence: true
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  paginates_per 5
  # attr_accessor :login
  has_one :cart
  has_many :orders
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  enum role: %i[admin client]

  validate :password_lower_case
  validate :password_uppercase
  validate :password_special_char
  validate :password_contains_number

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :username, :email, :password, presence: true, on: :create

  # Returns existing cart if exists otherwise creats new
  def ensure_cart
    cart.presence || create_cart
  end

  def login
    @login || username || email
  end

  # Checks if the password contains an upper_case character
  def password_uppercase
    return unless password&.match(/\p{Upper}/).nil?

    errors.add :password, ' must contain at least 1 uppercase '
  end

  def password_lower_case
    return unless password&.match(/\p{Lower}/).nil?

    errors.add :password, ' must contain at least 1 lowercase '
  end

  # Checks if the password contains a special character
  def password_special_char
    special = "?<>',?[]}{=-)(*&^%$#`~{}!@."
    regex = /[#{special.gsub(/./) { |char| "\\#{char}" }}]/
    return if password =~ regex

    errors.add :password, ' must contain special character'
  end

  # Checks if the password contains an integer between 0 to 9
  def password_contains_number
    return if password&.count('0-9')&.positive?

    errors.add :password, ' must contain at least one number'
  end

  # username/email validation
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  # search user
  def self.search(search)
    if search.present?
      where(' lower(username) LIKE :value or lower(email) LIKE :value ', value: "%#{search.downcase}%")
    else
      self
    end
  end

  # download the xls or csv files
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

module Admin
  # Class Orders
  class OrdersController < ApplicationController
    before_action :current_cart
    def index
      @orders = Order.all.order(:created_at)
    end

    def show
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  # User Controller
  class UsersController < ApplicationController
    before_action :find_user, only: %i[show edit update destroy]
    helper_method :sort_column, :sort_direction
    before_action :current_cart

    def index
      @users =
        User.search(params[:search])
            .order("#{sort_column} #{sort_direction}")
            .page params[:page]
      respond_to do |format|
        format.html
        format.xls { send_data @users.to_csv(col_sep: "\t") }
      end
      authorize @users
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_users_path
      else
        render 'new'
      end
    end

    def show; end

    def update
      if @user.update(user_params)
        redirect_to admin_users_path
      else
        render 'edit'
      end
    end

    def edit; end

    def destroy
      @user.destroy
      redirect_to admin_users_path
    end

    def delete_modal
      @user = User.find(params[:user_id])
    end

    private

    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : 'id'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
  end
end

app/controllers/api/admin/users_controller.rb
# frozen_string_literal: true

module Api
  # Admin
  module Admin
    # User Controller
    class UsersController < ApplicationController
      before_action :find_user, only: %i[show edit update destroy]
      helper_method :sort_column, :sort_direction
      before_action :authenticate_user!
      before_action :current_cart

      def index
        @users = User.all
      end

      def new; end

      def create
        @user = User.create(user_params)
      end

      def show; end

      def update
        if @user.update(user_params)
          redirect_to admin_users_path
        else
          render 'edit'
        end
      end

      def edit; end

      def destroy
        @user.destroy
        redirect_to admin_users_path
      end

      def delete_modal
        @user = User.find(params[:user_id])
      end

      private

      def find_user
        @user = User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:id, :username, :email, :password)
      end

      def sort_column
        User.column_names.include?(params[:sort]) ? params[:sort] : 'id'
      end

      def sort_direction
        %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
      end
    end
  end
end

app/controllers/user/carts_controller.rb
# frozen_string_literal: true

class User
  # Carts Controller
  class CartsController < ApplicationController
    def show
      @cart = current_cart
    end

    def destroy
      @cart = current_cart
      @cart.destroy

      session[:cart_id] = nil
      redirect_to root_path
    end
  end
end

app/controllers/user/order_items_controller.rb
# frozen_string_literal: true

class User
  # Order-Items Controller
  class OrderItemsController < ApplicationController
    def create
      result = CreateOrderItems.call(
        product_id: params[:product_id],
        current_cart: current_cart
      )
      @order_item = result.order_item
      if result.success?
        redirect_to user_cart_path(current_cart)
      else
        redirect_to user_products_path, alert: 'Error: Could not save to cart'
      end
    end

    def destroy
      @order_item = OrderItem.find(params[:id])
      @order_item.destroy
      redirect_to user_cart_path(current_cart)
    end

    private

    def order_item_params
      params.require(:order_item).permit(:quantity, :product_id, :cart_id)
    end
  end
end

app/controllers/user/orders_controller.rb
# frozen_string_literal: true

class User
  # Orders Controller
  class OrdersController < ApplicationController
    before_action :find_order, only: %i[show]
    skip_before_action :verify_authenticity_token
    def index
      @orders = Order.order(:created_at)
    end

    def show; end

    def new
      value = Coupon.validate_coupon(params[:coupon], current_cart) if params[:coupon].present?
      @coupon = current_cart.sub_total.to_i - value.to_i
      @order = Order.new
    end

    def create
      @order = current_order
      @order.update(order_params)
      current_cart.order_items.each do |item|
        @order.order_items << item
        item.cart_id = nil
        item.save
      end
      if @order.status == 0
        redirect_to user_order_path(order)
      else
        redirect_to root_path
      end
    end

    private

    def find_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:name, :email, :address, :payment, :user_id)
    end
  end
end

app/controllers/user/products_controller.rb
# frozen_string_literal: true

class User
  # ProductsController
  class ProductsController < ApplicationController
    before_action :current_cart
    def index
      @products = Product.order(:created_at)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module User
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module User
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module User
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module User
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password,
    #   :password_confirmation, :current_password])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module User
  # User Sessions Controller
  #
  class SessionsController < Devise::SessionsController
    before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_in_params
      devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module User
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Users Helper
module UsersHelper
end

app/views/user/orders/_coupon.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark">
  <h3 class ="text-light">Use Coupon</h3>
  <%= form_with url: new_user_order_path, method: 'get', remote: true do |f| %>
  <div class="field mb-3 text-start text-light">
    <%= f.label :coupon, class: "form-label" %>
    <%= f.text_field :coupon, autofocus: true, autocomplete: "title", class: "form-control" %>
  </div>
  <%= f.submit "Apply", class: 'actions mb-2 text-dark btn btn-warning mt-3' %>
  <h4 class ="text-light">Total Price: <%= current_cart.sub_total %></h4>

  <h4 class ="text-light">After Discount: <%= coupon %></h4>
<% end %>
</div>

app/views/user/orders/index.html.erb
<h2 class="text-light">All Orders</h2>
<% @orders.each do |order| %>
  <p>Name: <%= order.name %></p>
  <p>Email: <%= order.email %></p>
  <p>Order Items: </p>
  <ul>
    <% order.order_items.each do |item| %>
    <li><%= item.quantity %> x <%= item.product.title %></li>
    <% end %>
  </ul>
<% end %>

app/views/user/orders/new.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark">
  <%= link_to "Back", root_path  %>
  <h4 class="text-light"> Customer Information</h4>
  <%= form_for [:user,@order] do |f| %>
    <div class="text-light mt-2">
      <%= f.label :name %><br>
      <%= f.text_field :name, required: true, autofocus: true %>
    </div>
    <div class="text-light mt-2">
      <%= f.label :email %><br>
      <%= f.email_field :email, required: true %>
    </div>
    <div class="text-light mt-2">
      <%= f.label :address %><br>
      <%= f.text_area :address, required: true %>
    </div>
    <button type="button" class="btn btn-warning mt-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Payment Through?
    </button>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Payment Method</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="field">
              <%= f.radio_button :payment, "cash" %>
              <%= f.label :cash,"cash" %>
              <%= f.radio_button :payment, "card" %>
              <%= f.label :cash,"card" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            <%= button_to "Pay", payments_create_path, class: "btn btn-warning", remote: true %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div id='coupon'>
  <%= render 'coupon', coupon: @coupon %>
</div>

app/views/user/orders/new.js.erb
$('#coupon').html("<%= j render partial: 'coupon', locals: {coupon: @coupon} %>");

app/views/user/orders/show.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark">
  <%= link_to "Back", admin_orders_path  %>
  <h2 class="text-light">Order Details</h2>
  <h2>Order Details</h2>
  <div class="text-center">
    <% @order.order_items.each do |order_item| %>
    <h5>Order ID = <%= order_item.order_id %></h5>
      <p>Product ID = <%= order_item.product_id %></p>
      Product name = <%= order_item.product.title %></p>
      Product Description = <%= order_item.product.description %></p>
      Price = <%= order_item.product.price %></p>
    <% end %>
    <p>Total Price = <%= @order.price %></p>
    <%= link_to "Pay with card", payments_create_path, params: {id: @order.id},class: "btn btn-primary btn-lg", method: :post, remote: true %>
  </div>
</div>