config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  # get 'homepage', to: 'home#homepage'
  namespace :admin do
    resources :users do
      get :delete_modal
    end
    resources :products
    resources :categories
    resources :coupons
    resources :orders, only: %i[index show]
  end

  namespace :user do
    resources :products, only: %i[index]
    # since this cart is belongs to user and a user can only have a single cart so it should be resouce not resouces
    # as we do not have to pass any id to it, we can get the cart per user by using current_user.ensure_cart
    resource :cart, only: %i[show destroy]
    resources :order_items, only: %i[new create show destroy]
    resources :orders
  end
  post 'payments/create', to: 'payments#create'
  resources :invitations

  namespace :api do
    post :auth, to: 'authentication#create'
    namespace :admin do
      resources :users
      resources :products
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

# Order model
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  enum payment: %i[cash card]
  enum status: %i[complete pending]
  validates :name, :email, :address, presence: true
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

module Admin
  # Class Orders
  class OrdersController < ApplicationController
    before_action :current_cart
    def index
      @orders = Order.all.order(:created_at)
    end

    def show
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/user/orders_controller.rb
# frozen_string_literal: true

class User
  # Orders Controller
  class OrdersController < ApplicationController
    before_action :find_order, only: %i[show]
    skip_before_action :verify_authenticity_token
    def index
      @orders = Order.order(:created_at)
    end

    def show; end

    def new
      value = Coupon.validate_coupon(params[:coupon], current_cart) if params[:coupon].present?
      @coupon = current_cart.sub_total.to_i - value.to_i
      @order = Order.new
    end

    def create
      @order = current_order
      @order.update(order_params)
      current_cart.order_items.each do |item|
        @order.order_items << item
        item.cart_id = nil
        item.save
      end
      if @order.status == 0
        redirect_to user_order_path(order)
      else
        redirect_to root_path
      end
    end

    private

    def find_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:name, :email, :address, :payment, :user_id)
    end
  end
end

app/views/admin/orders/index.html.erb
<div class="container-fluid w-75 shadow mt-5 rounded border p-4 bg-dark" >
  <h2 class= "text-light">Orders</h2>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <th class="col text-light">ID</th>
        <th class="col text-light">User_ID</th>
        <th class="col text-light">Name</th>
        <th class="col text-light">Email</th>
        <th class="col text-light">Payment Method</th>
        <th class="col text-light"> Action </th>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td class="text-light"><%= order.id %></td>
            <td class="text-light"><%= order.user.id %></td>
            <td class="text-light"><%= order.name %></td>
            <td class="text-light"><%= order.email %></td>
            <td class="text-light"><%= order.payment %></td>
            <td class="text-light"><%= link_to 'Show Order', admin_order_path(order), class: "adminuserpath" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Back", root_path, class: :adminuserpath  %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark">
  <%= link_to "Back", admin_orders_path  %>
  <h2 class= "text-light">Details of order</h2>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <th class="col text-light">Product ID</th>
        <th class="col text-light">Product Name</th>
        <th class="col text-light">Product Description</th>
        <th class="col text-light">Product price</th>
      </thead>
      <tbody>
        <% @order.order_items.each do |order_item| %>
          <tr>
            <td class="text-light"><%= order_item.product.id %></td>
            <td class="text-light"><%= order_item.product.title %></td>
            <td class="text-light"><%= order_item.product.description %></td>
            <td class="text-light"><%= order_item.product.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>