config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  # get 'homepage', to: 'home#homepage'
  namespace :admin do
    resources :users do
      get :delete_modal
    end
    resources :products
    resources :categories
    resources :coupons
    resources :orders, only: %i[index show]
  end

  namespace :user do
    resources :products, only: %i[index]
    # since this cart is belongs to user and a user can only have a single cart so it should be resouce not resouces
    # as we do not have to pass any id to it, we can get the cart per user by using current_user.ensure_cart
    resource :cart, only: %i[show destroy]
    resources :order_items, only: %i[new create show destroy]
    resources :orders
  end
  post 'payments/create', to: 'payments#create'
  resources :invitations

  namespace :api do
    post :auth, to: 'authentication#create'
    namespace :admin do
      resources :users
      resources :products
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

# Product
class Product < ApplicationRecord
  paginates_per 5
  belongs_to :category
  belongs_to :coupon, optional: true
  has_many :order_items
  has_one_attached :image
  enum status: %i[published draft pending]
  validates :title, :price, :description, presence: true

  # search product
  def self.search(search)
    if search.present?
      where(' lower(products.title) LIKE :value ', value: "%#{search.downcase}%")
    else
      self
    end
  end

  # download the xls or csv files
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  # Product Controller
  class ProductsController < ApplicationController
    before_action :find_product, only: %i[show edit update destroy]
    helper_method :sort_column, :sort_direction

    def index
      @products =
        Product.search(params[:search])
               .order("#{sort_column} #{sort_direction}")
               .page params[:page]
      respond_to do |format|
        format.html
        format.xls { send_data @products.to_csv(col_sep: "\t") }
      end
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admin_products_path
      else
        render 'new'
      end
    end

    def show; end

    def update
      if @product.update(product_params)
        redirect_to admin_products_path
      else
        render 'edit'
      end
    end

    def edit; end

    def destroy
      @product.destroy
      redirect_to admin_products_path
    end

    private

    def find_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :price, :description, :status, :category_id, :image, :coupon_id)
    end

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : 'id'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
  end
end

app/controllers/api/admin/products_controller.rb
# frozen_string_literal: true

module Api
  # Admin
  module Admin
    # Product Controller
    class ProductsController < ApplicationController
      before_action :find_product, only: %i[show edit update destroy]
      helper_method :sort_column, :sort_direction

      def index
        @products = Product.all
      end

      def new; end

      def create
        @product = Product.create(product_params)
      end

      def show; end

      def update
        @product.update(product_params)
      end

      def edit; end

      def destroy
        @product.destroy
      end

      private

      def find_product
        @product = Product.find(params[:id])
      end

      def product_params
        params.require(:product).permit(:title, :price, :description, :status, :category_id, :image, :coupon_id)
      end

      def sort_column
        Product.column_names.include?(params[:sort]) ? params[:sort] : 'id'
      end

      def sort_direction
        %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
      end
    end
  end
end

app/controllers/user/products_controller.rb
# frozen_string_literal: true

class User
  # ProductsController
  class ProductsController < ApplicationController
    before_action :current_cart
    def index
      @products = Product.order(:created_at)
    end
  end
end

app/views/admin/products/_form.html.erb
<!-- form html -->
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark" >
  <h2 class= "text-light">Create Product</h2>
  <%= form_for [:admin, @product] do |f| %>

    <div class="field mb-3 text-start">
      <%= f.file_field :image, class: "form-control" %>
    </div>

    <div class="form-outline mb-4 text-light">
      <%= f.label :Title, class: "form-label" %>
      <%= f.text_field :title, required: true, autofocus: true, autocomplete: "title", class: "form-control" %>
    </div>

    <div class="form-outline mb-4 text-light">
      <%= f.label :Price, class: "form-label" %><br />
      <%= f.number_field :price, type: "number", required: true, autofocus: true, autocomplete: "price", class: "form-control", min: 1, placeholder: "Only Integer value" %>
    </div> 

    <div class="form-outline mb-4 text-light">
      <%= f.label :Description, class: "form-label" %>
      <%= f.text_area :description, required: true, autofocus: true, class: "form-control" %>
    </div>

    <div class="dropdown field mb-3 text-start text-light">
      <%= f.label :Select_Status, class: "form-label" %><br />
      <%= f.select :status, options_for_select(Product.statuses.keys.to_a.map {|key| [key.titleize, key]}), {}, class: "form-select" %>
    </div>

    <div class="dropdown field mb-3 text-start text-light">
      <%= f.label :select_category, class: "form-label" %><br />
      <%= f.select :category_id, options_for_select(Category.all.map {|key| [key.name, key.id]}), {}, class: "form-control form-select" %>
    </div>

    <%= f.submit "Create Product", class: 'actions mb-2 text-dark btn btn-warning mt-3' %>
  <% end %>
</div>

app/views/admin/products/index.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark" >
  <h2 class= "text-light">Products List</h2>
  <div class= "text-light"><hr></div>
   <div class="table-responsive">
      <%= form_tag admin_products_path, method: :get do %>
        <div class="float-end input-group w-50 input-group-sm mb-4" >
          <%= search_field_tag :search, params[:search], placeholder: "Search Here ", class:"form-control" %>
          <%= submit_tag "search", class: "btn btn-warning"%>
        </div>
      <% end %>
      <%= link_to(".xls Report", admin_products_path(format: :xls), class: "btn btn-warning text-wrap") %> 
      <%= link_to('Create Product', new_admin_product_path, class: "btn btn-warning text-wrap")%>
      <table class="table table-sm">
        <thead>
          <th class="col text-light"><%= sortable "id","ID" %></th>
          <th class="col text-light"><%= sortable "title","Title" %></th>
          <th class="col text-light"><%= sortable "price","Price" %></th>
          <th class="col text-light"><%= sortable "status","Status" %></th>
          <th class="col text-light">Action</th>
        </thead>
        <tbody class="text-light">
          <% @products.each do |product| %>
            <tr>
              <td><%= product.id %></td>
              <td><%= product.title %></td>
              <td><%= product.price %></td>
              <td><%= product.status %></td>
              <td class ="link-warning">
                <%= link_to 'Show', admin_product_path(product), class: :adminuserpath %>
                <%= link_to "Edit", edit_admin_product_path(product), class: :adminuserpath %>
                <%= link_to 'Delete', admin_product_path(product), method: :delete, data: {Confirm: "Are you sure?"}, class: :adminuserpath %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @products, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center",
      nav_class: "d-inline-block" %><br>
      <%= link_to "Back", root_path , class: :adminuserpath %> 
    </div>
</div>

app/views/admin/products/show.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark">
  <%= link_to "Back", admin_products_path  %>
  <div class="text-light text-center">
    <h3>Product:<%= @product.id %></h3>
    <p> Title: <%= @product.title %></p>
    <p> Price: <%= @product.price %></p>
    <p> Description: <%= @product.description %></p>
    <p> Status: <%= @product.status %></p>
  </div>
</div>