config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  # get 'homepage', to: 'home#homepage'
  namespace :admin do
    resources :users do
      get :delete_modal
    end
    resources :products
    resources :categories
    resources :coupons
    resources :orders, only: %i[index show]
  end

  namespace :user do
    resources :products, only: %i[index]
    # since this cart is belongs to user and a user can only have a single cart so it should be resouce not resouces
    # as we do not have to pass any id to it, we can get the cart per user by using current_user.ensure_cart
    resource :cart, only: %i[show destroy]
    resources :order_items, only: %i[new create show destroy]
    resources :orders
  end
  post 'payments/create', to: 'payments#create'
  resources :invitations

  namespace :api do
    post :auth, to: 'authentication#create'
    namespace :admin do
      resources :users
      resources :products
    end
  end
end

app/models/coupon.rb
# frozen_string_literal: true

# coupon file
class Coupon < ApplicationRecord
  paginates_per 5

  validates :name, :price, presence: true

  has_many :products

  def self.search(search)
    if search.present?
      where('lower(coupons.name) LIKE :value', value: "%#{search.downcase}%")
    else
      self
    end
  end

  # download the xls or csv files
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |coupon|
        csv << coupon.attributes.values_at(*column_names)
      end
    end
  end

  def coupon_for_products(products)
    products = products.compact.reject!(&:empty?)
    Product.where(id: products).update_all(coupon_id: id)
  end

  def self.validate_coupon(coupon, cart)
    value = Coupon.find_by(name: coupon).present? ? Coupon.find_by(name: coupon).price : 0

    if value.positive?
      count = cart.products.where('coupon_id = ?', Coupon.find_by(name: coupon).id).count
      value *= count
    end
    value
  end
end

app/controllers/admin/coupons_controller.rb
# frozen_string_literal: true

module Admin
  # Coupon Controller
  class CouponsController < ApplicationController
    before_action :find_coupon, only: %i[show edit update destroy]
    helper_method :sort_column, :sort_direction

    def index
      @coupons =
        Coupon.search(params[:search])
              .order("#{sort_column} #{sort_direction}")
              .page params[:page]
      respond_to do |format|
        format.html
        format.xls { send_data @coupons.to_csv(col_sep: "\t") }
      end
    end

    def new
      @coupon = Coupon.new
    end

    def create
      @coupon = Coupon.new(coupon_params)
      ActiveRecord::Base.transaction do
        @coupon.save!
        @coupon.coupon_for_products(params[:coupon][:products])
        redirect_to admin_coupons_path, notice: 'Disocunt is saved.'
      rescue StandardError
        render 'new'
      end
    end

    def show; end

    def update
      if @coupon.update(coupon_params)
        redirect_to admin_coupons_path
      else
        render 'edit'
      end
    end

    def edit; end

    def destroy
      @coupon.destroy
      redirect_to admin_coupons_path
    end

    private

    def find_coupon
      @coupon = Coupon.find(params[:id])
    end

    def coupon_params
      params.require(:coupon).permit(:name, :price)
    end

    def sort_column
      Coupon.column_names.include?(params[:sort]) ? params[:sort] : 'id'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
  end
end

app/views/admin/coupons/_form.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark" >
  <h2 class= "text-light"> New Coupon </h2>
  <%= form_for [:admin, @coupon] do |f| %>
    <div class="fform-outline mb-4 text-light">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, required: true, autofocus: true, autocomplete: "name", class: "form-control" %>
    </div>

    <div class="form-outline mb-4 text-light">
      <%= f.label :price, class: "form-label" %>
      <%= f.number_field :price, required: true, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "Only Integer value" %>
    </div>
    <div class="dropdown field mb-3 text-start text-light">
      <%= f.label :select_product, class: "form-label" %><br />
      <%= f.select :products, options_for_select(Product.all.map {|key| [key.title, key.id]}), {}, multiple: true, class: "form-control form-select" %>
    </div>

    <%= f.submit "Create Coupon", class: 'actions mb-2 text-dark btn btn-warning mt-3' %>
  <% end %>
</div>

app/views/admin/coupons/edit.html.erb
<%= render 'form' %>

app/views/admin/coupons/index.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark" >
  <h2 class= "text-light">Coupons List</h2>
  <div class= "text-light"><hr></div>
   <div class="table-responsive">
      <%= form_tag admin_coupons_path, method: :get do %>
        <div class="float-end input-group w-50 input-group-sm mb-4" >
          <%= search_field_tag :search, params[:search], placeholder: "Search Here ", class:"form-control" %>
          <%= submit_tag "search", class: "btn btn-warning"%>
        </div>
      <% end %>
      <%= link_to(".xls Report", admin_coupons_path(format: :xls), class: "btn btn-warning text-wrap") %> 
      <%= link_to('Create Coupon', new_admin_coupon_path, class: "btn btn-warning text-wrap")%>
      <table class="table table-sm">
        <thead>
          <th class="col text-light"><%= sortable "id","ID" %></th>
          <th class="col text-light"><%= sortable "name","Name" %></th>
          <th class="col text-light"><%= sortable "price","Price" %></th>
          <th class="col text-light">Action</th>
        </thead>
        <tbody class="text-light">
          <% @coupons.each do |coupon| %>
            <tr>
              <td><%= coupon.id %></td>
              <td><%= coupon.name %></td>
              <td><%= coupon.price %></td>
              <td class ="link-warning">
                <%= link_to 'Show', admin_coupon_path(coupon), class: :adminuserpath %>
                <%= link_to "Edit", edit_admin_coupon_path(coupon), class: :adminuserpath %>
                <%= link_to 'Delete', admin_coupon_path(coupon), method: :delete, data: {Confirm: "Are you sure?"}, class: :adminuserpath %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @coupons, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center",
      nav_class: "d-inline-block" %><br>
      <%= link_to "Back", root_path , class: :adminuserpath %> 
    </div>
</div>

app/views/admin/coupons/new.html.erb
<%= render 'form' %>

app/views/admin/coupons/show.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg-dark">
  <%= link_to "Back", admin_coupons_path  %>
  <div class="text-light text-center">
    <h3>Product:<%= @coupon.id %></h3>
    <p> Title: <%= @coupon.name %></p>
    <p> Price: <%= @coupon.price %></p>
    <p> Products:
      <% @coupon.products.each do |product| %>
        <%= product.title %><br>
      <% end %>
    </p>
    </p>
  </div>
</div>